### ISSUE TITLE
Expected version roadmap

### ISSUE THREAD

**Issue by empt-ak** [empt-ak/meditor#110]
- [x] 0.4 websockets and new configurations
- [ ] 0.5 type manager done
- [ ] 0.6 form and cmis integration done
- [ ] 0.7 spring integration implemented with plugins
- [ ] 0.8 95% code coverage 
- [ ] 0.9 missing and additional functionality
- [ ] 1.0 code polishing
