### ISSUE TITLE
Rework StreamNetwork into organization

### ISSUE THREAD

**Issue by empt-ak** [empt-ak/meditor#81]
## Steps
- [x] Merge StreamNetwork into UserGroup
- [x] Rename UserGroup to organization
- [x] merge DAO tests
- [x] fix DAO tests
- [x] merge integration tests
- [x] merge and delete AOP
- [x] fix integration tests
- [x] Merge Controllers
- [x] remove and add formatters
- [x] jsp and javascript files according to new controllers
- [x] remove permission
- [x] merge permission into organization
- [x] when organization is created notification is set to organization with request for approval #96 

## Key functionality
- [x] anyone can create Organization. Such organization has no permission
- [x] users can create custom permission, so when cmis object is created, it can be restricted to certain organization
- [x] Organizations have separate jsp view
- [x] properties from groups and networks are inherited such as visibility

## tasks todo
- [x] when organization is created without owner, then current logged user is set as owner
- [x] when creating organization, owner is added as member aswell.
