### ISSUE TITLE
Notification System

### ISSUE THREAD

**Issue by empt-ak** [empt-ak/meditor#91]
## Reading

http://activitystrea.ms/specs/json/1.0/
## Tasks
- [x] create notification object based on reading
- [x] create service used for fetching notifications and setting them as read
- [x] when something happens and is part of notification events, then event is published
- [x] choose whether event is send by code in service method, or it is driven by aspect
- [x] events are not part of api
